{
  "access_token": "1234567890abcdefghijklmnopqrstuvwxyz",
  "repository": {
    "query": {
      "user": "mccurdyc",
      "language": "golang",
      "stars": 1
    }
  },
  "code": {
    "query": {
      "file": "README.md"
    }
  }
}
